kind: pipeline
name: default

steps:
  - name: build
    image: node:11-alpine
    pull: always
    commands:
      - node -v
      - npm -v
      - npm i
      - npm run build

  - name: deploy
    image: cupcakearmy/drone-deploy
    pull: always
    environment:
      PLUGIN_KEY:
        from_secret: ssh_key
    settings:
      host: nicco.io
      user: root
      port: 1312
      target: /srv/web/reh
      sources:
        - ./dist
        - ./docker-compose.yml
        - ./docker-compose.prod.yml
      commands:
        - docker-compose -f docker-compose.yml -f docker-compose.prod.yml down
        - docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
    when:
      event: push
      branch: master