version: '3'

services:
  frontend:
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.docker.network=traefik
      - traefik.backend=reh
      - traefik.frontend.rule=Host:xn--rehfnger-3za.club

networks:
  traefik:
    external: true
