version: '3'

services:
  frontend:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./dist:/srv/dist
      - ./index.html:/srv/index.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf